accounts/urls.py
from django.urls import include, path

from accounts import views

urlpatterns = [
    path("register-user/", views.register_user, name="register-user"),
    path("register-vendor/", views.register_vendor, name="register-vendor"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("my-account/", views.my_account, name="my-account"),
    path("customer-dashboard/", views.customer_dashboard, name="customer-dashboard"),
    path("vendor-dashboard/", views.vendor_dashboard, name="vendor-dashboard"),
    path("activate/<uidb64>/<token>", views.activate, name="activate"),
    path("forgot-password/", views.forgot_password, name="forgot-password"),
    path(
        "forgot-password-validation/<uidb64>/<token>/",
        views.forgot_password_validation,
        name="forgot-password-validation",
    ),
    path("reset-password/", views.reset_password, name="reset-password"),
    path("vendor/", include("vendor.urls")),
    path("customer/", include("customer.urls")),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from accounts.views import index
from marketplace.views import cart, checkout, search

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("cart/", cart, name="cart"),
    path("search/", search, name="search"),
    path("checkout/", checkout, name="checkout"),
    path("accounts/", include("accounts.urls")),
    path("marketplace/", include("marketplace.urls")),
    path("orders/", include("orders.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.gis.db import models as gis_models
from django.contrib.gis.geos import Point
from django.db import models

from .validators import valid_image_extensions

# Create your models here.


class UserManager(BaseUserManager):

    def create_user(self, first_name, last_name, username, email, password=None):
        """
        Create a new User instance based on the given
        first name, last name, username, email and password.
        """
        if not first_name:
            raise ValueError("User must have first name.")
        if not last_name:
            raise ValueError("User must have last name.")
        if not username:
            raise ValueError("User must have username.")
        if not email:
            raise ValueError("User must have email address.")

        user = self.model(
            first_name=first_name,
            last_name=last_name,
            username=username,
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, username, email, password=None):
        """
        Create a new Super User instance based on the given
        first name, last name, username, email and password.
        """
        user = self.create_user(
            first_name=first_name,
            last_name=last_name,
            username=username,
            email=email,
            password=password,
        )

        user.is_active = True
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True

        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    VENDOR = 1
    CUSTOMER = 2

    ROLE_CHOICES = [(VENDOR, "VENDOR"), (CUSTOMER, "CUSTOMER")]

    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    username = models.CharField(max_length=255, unique=True)
    email = models.EmailField(max_length=255, unique=True)
    phone = models.CharField(max_length=20, unique=True, null=True, blank=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, null=True, blank=True)

    # Date fields
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    # Boolean fields
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = [
        "first_name",
        "last_name",
        "username",
    ]

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

    def get_role(self):
        return "Vendor" if self.role == 1 else "Customer"


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    profile_picture = models.ImageField(
        upload_to="users/profile_picture",
        blank=True,
        null=True,
        validators=[valid_image_extensions],
    )
    cover_photo = models.ImageField(
        upload_to="users/cover_photo",
        blank=True,
        null=True,
        validators=[valid_image_extensions],
    )
    address = models.CharField(max_length=255, blank=True, null=True)
    country = models.CharField(max_length=50, blank=True, null=True)
    state = models.CharField(max_length=50, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    pin_code = models.CharField(max_length=25, blank=True, null=True)
    latitude = models.CharField(max_length=25, blank=True, null=True)
    longitude = models.CharField(max_length=25, blank=True, null=True)
    location = gis_models.PointField(null=True, blank=True, srid=4326)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.email

    def save(self, *args, **kwargs):
        if self.longitude and self.latitude:
            self.location = Point(float(self.longitude), float(self.latitude))
        return super(UserProfile, self).save(*args, **kwargs)

accounts/views.py
import datetime

from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.tokens import default_token_generator
from django.contrib.gis.db.models.functions import Distance
from django.contrib.gis.geos import GEOSGeometry
from django.contrib.gis.measure import D
from django.shortcuts import redirect, render
from django.template.defaultfilters import slugify
from django.utils.http import urlsafe_base64_decode

from accounts import forms as accounts_forms
from accounts import models as accounts_models
from orders import models as orders_models
from vendor import forms as vendor_forms
from vendor import models as vendor_models

from .utils import (
    check_role_customer,
    check_role_vendor,
    detect_user,
    send_verification_email,
)


def get_or_set_current_location(request):
    if "lat" in request.session:
        lat = request.session["lat"]
        lng = request.session["lng"]
        return lng, lat
    elif "lat" in request.GET:
        lat = request.GET.get("lat")
        lng = request.GET.get("lng")

        request.session["lat"] = lat
        request.session["lng"] = lng
        return lng, lat
    else:
        return None


def index(request):
    if get_or_set_current_location(request) is not None:

        point = GEOSGeometry("POINT(%s %s)" % (get_or_set_current_location(request)))

        vendors = (
            vendor_models.Vendor.objects.filter(
                user_profile__location__distance_lte=(point, D(km=100)),
                user__is_active=True,
                is_approved=True,
            )
            .annotate(distance=Distance("user_profile__location", point))
            .order_by("distance")
        )
        for vendor in vendors:
            vendor.kms = round(vendor.distance.km, 1)
    else:
        vendors = vendor_models.Vendor.objects.filter(
            user__is_active=True, is_approved=True
        )

    context = {"top_vendors": vendors[:8], "popular_vendors": vendors[:8]}
    return render(request, "accounts/index.html", context)


def register_user(request):
    form = accounts_forms.RegisterUserForm()

    if request.user.is_authenticated:
        messages.warning(request, "You already signed up.")
        return redirect(my_account)

    if request.method == "POST":
        form = accounts_forms.RegisterUserForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data["password"]
            user = form.save(commit=False)
            user.set_password(password)
            user.role = accounts_models.User.CUSTOMER
            user.save()

            # send verification email
            mail_subject = "Please activate your account"
            email_template = "emails/account_verification_email.html"
            send_verification_email(request, user, mail_subject, email_template)

            messages.success(request, "Your account has been created successfully!")
            return redirect("login")

    context = {"form": form}

    return render(request, "accounts/register_user.html", context)


def register_vendor(request):
    user_form = accounts_forms.RegisterUserForm()
    vendor_form = vendor_forms.VendorForm()

    if request.user.is_authenticated:
        messages.warning(request, "You already signed up.")
        return redirect(my_account)

    if request.method == "POST":
        user_form = accounts_forms.RegisterUserForm(request.POST)
        vendor_form = vendor_forms.VendorForm(request.POST, request.FILES)
        if user_form.is_valid() and vendor_form.is_valid():
            # save the user instance
            user_password = user_form.cleaned_data["password"]
            user = user_form.save(commit=False)
            user.set_password(user_password)
            user.role = accounts_models.User.VENDOR
            user.save()

            # save the vendor instance
            vendor = vendor_form.save(commit=False)
            vendor.user = user
            user_profile = accounts_models.UserProfile.objects.get(user=user)
            vendor.user_profile = user_profile
            vendor.slug = f"{slugify(vendor.name)}-{str(user.pk)}"
            vendor.save()

            # send verification email
            mail_subject = "Please activate your account"
            email_template = "emails/account_verification_email.html"
            send_verification_email(request, user, mail_subject, email_template)

            messages.success(
                request,
                "Your account has been registered successfully!\nPlease wait for the approval.",
            )

        return redirect("login")

    context = {"user_form": user_form, "vendor_form": vendor_form}
    return render(request, "accounts/register_vendor.html", context)


def login_user(request):
    if request.user.is_authenticated:
        messages.info(request, "You are already logged in!")
        return redirect("my-account")

    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        user = auth.authenticate(email=email, password=password)

        if user is not None:
            auth.login(request, user)
            messages.success(request, "You are now logged in.")
            return redirect("my-account")
        else:
            messages.error(request, "Invalid email or password.")
            return redirect("login")

    return render(request, "accounts/login.html")


@login_required(login_url="login")
def logout_user(request):
    auth.logout(request)
    messages.info(request, "You are logged out")
    return redirect("login")


@login_required(login_url="login")
def my_account(request):
    user = request.user
    redirect_to = detect_user(user)
    return redirect(redirect_to)


@login_required(login_url="login")
@user_passes_test(check_role_customer)
def customer_dashboard(request):
    orders = orders_models.Order.objects.filter(
        user=request.user, is_ordered=True
    ).order_by("-created_at")
    context = {
        "recent_orders": orders[:10],
        "orders_count": orders.count(),
    }
    return render(request, "accounts/customer_dashboard.html", context)


@login_required(login_url="login")
@user_passes_test(check_role_vendor)
def vendor_dashboard(request):
    vendor = vendor_models.Vendor.objects.get(user=request.user)
    orders = orders_models.Order.objects.filter(
        vendors__in=[vendor.id], is_ordered=True
    ).order_by("-created_at")

    total_revenue = 0

    for order in orders:
        total_revenue += order.get_total_by_vendor()["grand_total"]

    month_revenue = 0
    current_month = datetime.datetime.now().month
    current_month_orders = orders_models.Order.objects.filter(
        vendors__in=[vendor.id], is_ordered=True, created_at__month=current_month
    ).order_by("-created_at")

    for order in current_month_orders:
        month_revenue += order.get_total_by_vendor()["grand_total"]

    context = {
        "recent_orders": orders[:10],
        "orders_count": orders.count(),
        "total_revenue": total_revenue,
        "month_revenue": month_revenue,
    }
    return render(request, "accounts/vendor_dashboard.html", context)


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = accounts_models.User._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, accounts_models.User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()

        messages.success(request, "Congratulations! Your account is activated.")
        return redirect("my-account")
    else:
        messages.error(request, "Invalid activation link.")
        return redirect("my-account")


def forgot_password(request):
    if request.method == "POST":
        email = request.POST.get("email")

        if accounts_models.User.objects.filter(email=email).exists:
            user = accounts_models.User.objects.get(email__exact=email)

            mail_subject = "Reset Your Password"
            email_template = "emails/reset_password.html"
            send_verification_email(request, user, mail_subject, email_template)

            messages.success(
                request, "Password reset link has been sent to your email address."
            )
            return redirect("login")
        else:
            messages.error(request, "Account does not exist!")
            return redirect("forgot-password")
    return render(request, "accounts/forgot_password.html")


def forgot_password_validation(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = accounts_models.User.objects.get(pk=uid)
    except (
        ValueError,
        TypeError,
        KeyError,
        OverflowError,
        accounts_models.User.DoesNotExist,
    ):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session["uid"] = uid
        messages.info(request, "Please reset your password")
        return redirect("reset-password")
    else:
        messages.error(request, "This link has been expired!")
        return redirect("my-account")


def reset_password(request):
    if request.method == "POST":
        password = request.POST.get("password")
        confirm_password = request.POST.get("confirm_password")

        if password and confirm_password and password == confirm_password:
            pk = request.session.get("uid")
            user = accounts_models.User.objects.get(pk=pk)
            user.set_password(password)
            user.is_active = True
            user.save()

            messages.success(request, "Password reset successful")
            return redirect("login")
        else:
            messages.error(request, "Password does not match")

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    FoodOnline | Home
{% endblock title %}
{% block content %}
    <!-- Main Section Start -->
    <div class="main-section">
        <!-- Home Pages Elements Start -->
        <!-- Main Search Start -->
        <div class="page-section nopadding cs-nomargin"
             style="padding-top: 200px; padding-bottom: 150px; margin-bottom: 0px; background: url({% static 'assets/extra-images/bg-image1.jpg' %}) no-repeat center / cover;">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                        <div class="element-title">
                            <h1 style="font-size: 40px; color: #505050; text-transform: uppercase; line-height: 50px; margin-bottom: 25px; text-align:center;">
                                We are in the business of food<br>our restaurants do</h1>
                            <p style="font-size: 18px; letter-spacing: 1px; color: #505050; text-align:center;">
                                Ridiculus sociosqu cursus neque cursus curae ante scelerisque vehicula.
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                        <div class="main-search fancy bg-holder">
                            <form action="{% url 'search' %}" method="GET">
                                <div class="row">
                                    <div class="col-lg-4 col-md-4 col-sm-3 col-xs-12">
                                        <div class="field-holder">
                                            <input type="text" name="keyword"
                                                   placeholder="Restaurant name or Food Name">
                                        </div>
                                    </div>
                                    <div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
                                        <div class="field-holder">
                                            <ul>
                                                <li class="select-location">
                                                    <div class="foodbakery-locations-fields-group foodbakery-focus-out">
                                                        <span class="foodbakery-search-location-icon"><i
                                                                class="icon-location"></i></span>
                                                        <input type="text" class="location-field-text filter"
                                                               name="address" id="id_address" required
                                                               placeholder="All Locations">
                                                        <input type="text" id="id_latitude" name="lat" value=""
                                                               style="display: none">
                                                        <input type="text" id="id_longitude" name="lng" value=""
                                                               style="display: none">
                                                    </div>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                        <select name="radius" id="radius" style="height: 50px;" required>
                                            <option value="" selected>Choose Radius</option>
                                            <option value="5">5 Km</option>
                                            <option value="10">10 Km</option>
                                            <option value="15">15 Km</option>
                                            <option value="25">25 Km</option>
                                            <option value="50">50 Km</option>
                                            <option value="75">75 Km</option>
                                            <option value="100">100 Km</option>
                                        </select>
                                    </div>
                                    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                                        <div class="field-holder">
                                            <input type="submit" value="Search">
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Main Search End -->
        {% if top_vendors %}
            <!-- Top Restaurants Section Start -->
            <div class="page-section nopadding cs-nomargin"
                 style="margin-top: 0px;padding-top: 60px;padding-bottom: 0px;margin-bottom: 0px;background: #ffffff;">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="element-title align-left">
                                <h2>Top Restaurants</h2>
                                <p>Explore restaurants, bars, and cafés by locality</p>
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"
                             style="padding-right: 0 !important; padding-left: 0 !important;">
                            <div class="company-logo">
                                <ul>
                                    {% for vendor in top_vendors %}
                                        <li class="has-border">
                                            <figure>
                                                <a href="{% url 'vendor-details' vendor.slug %}">
                                                    {% if vendor.user_profile.profile_picture %}
                                                        <img src="{{ vendor.user_profile.profile_picture.url }}"
                                                             class="attachment-full size-full wp-post-image"
                                                             alt="{{ vendor.name }}'s logo">
                                                    {% else %}
                                                        <img src="{% static 'assets/extra-images/listing-logo18.png' %}"
                                                             class="attachment-full size-full wp-post-image" alt="logo">
                                                    {% endif %}
                                                </a>
                                            </figure>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Top Restaurants Section End -->
        {% endif %}
        {% if popular_vendors %}
            <!-- Choose From Most Popular Listing Start -->
            <div class="page-section nopadding cs-nomargin"
                 style="margin-top: 0px;padding-top: 60px;padding-bottom: 50px;margin-bottom: 0px;background: #ffffff;">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="element-title align-center">
                                <h2>Choose From Most Popular Restaurants</h2>
                                <p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="listing fancy">
                                <ul class="row">
                                    {% for vendor in popular_vendors %}
                                        <li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                            <div class="list-post featured">
                                                <div class="img-holder">
                                                    <figure>
                                                        <a href="{% url 'vendor-details' vendor.slug %}">
                                                            {% if vendor.user_profile.profile_picture %}
                                                                <img src="{{ vendor.user_profile.profile_picture.url }}"
                                                                     class="img-thumb wp-post-image"
                                                                     alt="{{ vendor.name }}'s logo">
                                                            {% else %}
                                                                <img src="{% static 'assets/extra-images/listing-logo18.png' %}"
                                                                     class="img-thumb wp-post-image" alt="logo">
                                                            {% endif %}
                                                        </a>
                                                    </figure>
                                                    {% if vendor.is_open %}
                                                        <span class="restaurant-status open">
                                                    <em class="bookmarkRibbon"></em>
                                                    Open
                                                </span>
                                                    {% else %}
                                                        <span class="restaurant-status close">
                                                    <em class="bookmarkRibbon"></em>
                                                    Closed
                                                </span>
                                                    {% endif %}
                                                </div>
                                                <div class="text-holder">
                                                    <div class="post-title">
                                                        <h5>
                                                            <a href="{% url 'vendor-details' vendor.slug %}">{{ vendor.name | title }}</a>
                                                        </h5>
                                                    </div>
                                                    {% if vendor.user_profile.state and vendor.user_profile.city and vendor.user_profile.pin_code %}
                                                        <address>
                                                            {{ vendor.user_profile.state | safe | title }}, {{ vendor.user_profile.city | safe | title }}, {{ vendor.user_profile.pin_code }}
                                                        </address>
                                                    {% endif %}
                                                    {% if vendor.kms %}
                                                        <span><small><b>{{ vendor.kms }}</b>away from your current location</small></span>
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Choose From Most Popular Listing End -->
        {% endif %}

        <!-- Home Pages Elements End  -->
    </div>
    <!-- Main Section End -->
{% endblock content %}